name: node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ["8.0"]

    env:
      DBHOST: ${{ secrets.DBHOST }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Use Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      # Spin up MongoDB Docker instance
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Create .env file with secrets
      - name: Create .env file
        run: |
          echo "DBHOST=${{ secrets.DBHOST }}" >> .env
          echo "TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}" >> .env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install

      # NPM Install, build, and test
      - name: NPM Install, build and test
        run: |
          npm install
          npm run build
          npm test
        continue-on-error: false

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Dette sikrer, at deploy kun kører ved succesfuld test
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
