name: node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        mongodb-version: ["6.0", "7.0", "8.0"]

    env:
      DBHOST: ${{ secrets.DBHOST }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

    steps:
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      # Spin up MongoDB Docker instance in GitHub Actions
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      # Create .env file (get rid of dotenv-flow errors)
      - name: Create .env file
        run: |
          touch .env
          echo "${{secrets.API}}" >> .env

      - name: NPM Install, build and test
        run: |
          npm install
          npm run build
          npm test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  
    if: ${{ success() }}
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
