name: node.js CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    env:
      DBHOST: ${{ secrets.DBHOST }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install, build and test
        run: |
          npm install
          npm run build
          npm test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test  
    if: ${{ success() }}
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
